<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-23T00:49:24 IST" name="Default suite" finished-at="2024-07-23T00:49:31 IST" duration-ms="6931">
    <groups>
    </groups>
    <test started-at="2024-07-23T00:49:24 IST" name="Default test" finished-at="2024-07-23T00:49:31 IST" duration-ms="6931">
      <class name="com.npvtest.testcases.ContactUsDataDriven">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.npvtest.testcases.ContactUsDataDriven@51891008]" started-at="2024-07-23T00:49:24 IST" name="setup" finished-at="2024-07-23T00:49:31 IST" duration-ms="6646" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="VerifyContactFormPage(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.npvtest.testcases.ContactUsDataDriven@51891008]" started-at="2024-07-23T00:49:31 IST" name="VerifyContactFormPage" data-provider="ContactFormDataProvider" finished-at="2024-07-23T00:49:31 IST" duration-ms="15" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void com.npvtest.testcases.ContactUsDataDriven.VerifyContactFormPage(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: VerifyContactFormPage([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.lang.String) test name,(java.lang.String) test@test.com,(java.lang.String) test subject,(java.lang.String) test message]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.npvtest.testcases.ContactUsDataDriven.VerifyContactFormPage(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: VerifyContactFormPage([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.lang.String) test name,(java.lang.String) test@test.com,(java.lang.String) test subject,(java.lang.String) test message]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:915)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyContactFormPage -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.npvtest.testcases.ContactUsDataDriven@51891008]" started-at="2024-07-23T00:49:31 IST" name="teardown" finished-at="2024-07-23T00:49:31 IST" duration-ms="223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.npvtest.testcases.ContactUsDataDriven -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
